{% set name = "dwave-tabu" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-tabu-{{ version }}.tar.gz
  sha256: dcc73883ec491dea2656c8239dc66e9c9871e7f75852be57ea4cec6bccd48d54

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy 1.20                             # [build_platform != target_platform and py<310]
    - numpy                                  # [build_platform != target_platform and py>=310]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.23,<3.0
    - numpy 1.20  # [py<310]
    - numpy       # [py>=310]
    - setuptools >=46.4.0
    - pip
    - python
    - wheel >=0.30.0
  run:
    - dimod >=0.9.0,<0.13.0
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - tabu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-tabu
  summary: Optimized Tabu solver for QUBOs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
